"""Daily data converter for detailed_daily_operations.csv compatibility.

Converts environment state to database-ready records matching R version's 23-column format.
"""

from typing import Dict, List
from simulation.aircraft import Aircraft


def convert_state_to_daily_records(
    state: Dict,
    episode_id: int,
    tokens_available: int,
    session_id: int,
    episode_number: int
) -> List[Dict]:
    """Convert environment state to daily_data records for database.

    Args:
        state: Environment state dictionary from env.get_state()
        episode_id: Database episode ID
        tokens_available: Current token count (single pool)
        session_id: Session identifier
        episode_number: Episode number within session

    Returns:
        List of dictionaries (one per aircraft) with 22 fields matching daily_data table
        (excluding daily_id which is auto-generated)
    """
    records = []

    # Extract day and aircraft list
    current_day = state["sim_day"]
    aircraft_list = state["aircraft"]

    # Convert each aircraft to a record
    for aircraft in aircraft_list:
        record = _convert_aircraft_to_record(
            aircraft=aircraft,
            episode_id=episode_id,
            day=current_day,
            tokens_available=tokens_available,
            session_id=session_id,
            episode_number=episode_number
        )
        records.append(record)

    return records


def _convert_aircraft_to_record(
    aircraft: Aircraft,
    episode_id: int,
    day: int,
    tokens_available: int,
    session_id: int,
    episode_number: int
) -> Dict:
    """Convert single aircraft state to database record.

    Args:
        aircraft: Aircraft object
        episode_id: Database episode ID
        day: Simulation day
        tokens_available: Current token count
        session_id: Session identifier
        episode_number: Episode number

    Returns:
        Dictionary with 22 fields (daily_id excluded, auto-generated by database)
    """
    # Map status to R format
    status = _map_status(aircraft)

    # Map queue position to R format
    queue_position = _map_queue_position(aircraft)

    # Convert booleans to integers (SQLite uses 0/1)
    flew_today = 1 if aircraft.flew_today else 0
    flight_failure_today = 1 if aircraft.flight_failure_today else 0

    # Build record dictionary (field names match INSERT statement in sql_integration.py)
    return {
        "episode_id": episode_id,
        "day": day,
        "aircraft_id": aircraft.id,
        "decision": aircraft.todays_decision if aircraft.todays_decision else "none",
        "true_rul": aircraft.true_rul,
        "observed_rul": aircraft.observed_rul,
        "total_flight_hours": aircraft.total_flight_hours,
        "todays_flight_hours": aircraft.todays_flight_hours,
        "hours_since_minor_phase": aircraft.hours_since_minor_phase,
        "hours_since_major_phase": aircraft.hours_since_major_phase,
        "status": status,
        "flew_today": flew_today,
        "flight_failure_today": flight_failure_today,
        "maintenance_started": aircraft.maintenance_started_today,
        "maintenance_completed": aircraft.maintenance_completed_today,
        "days_in_maintenance": aircraft.maintenance_days_remaining,
        "queue_position": queue_position,
        # Single token pool - all three columns get same value
        "tokens_remaining_preventive": tokens_available,
        "tokens_remaining_minor_phase": tokens_available,
        "tokens_remaining_major_phase": tokens_available,
        "episode": episode_number,
        "session_id": session_id,
    }


def _map_status(aircraft: Aircraft) -> str:
    """Map aircraft status to R format.

    Args:
        aircraft: Aircraft object

    Returns:
        Status string: "FMC", "NMC", or "maintenance_{type}"
    """
    if aircraft.in_maintenance:
        # In maintenance - format as "maintenance_{type}"
        return f"maintenance_{aircraft.maintenance_type}"
    else:
        # Use base status ("FMC" or "NMC")
        return aircraft.status


def _map_queue_position(aircraft: Aircraft) -> str:
    """Map aircraft queue state to R format.

    Args:
        aircraft: Aircraft object

    Returns:
        Queue position string: "none", "preventive_queue", or "phase_queue"
    """
    if aircraft.in_queue:
        # In queue - format as "{queue_type}_queue"
        return f"{aircraft.queue_type}_queue"
    else:
        return "none"
